<?php

use Ghratzoo\CustomHeader\Block\CustomHeader;

/** @var CustomHeader $block */
?>
<div class="container">
    <div id="header-left">
        <ul id="additional-info">
            <?php foreach ($block->getAdditionalInfo() as $additionalInfo): ?>
            <li><?= $additionalInfo ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div id="header-right">
        <span id="phone-number"><?php print_r($block->getPhoneNumber()) ?></span>
        <span class="support-menu">&#9432;</span><div class="customer-welcome">
            <div
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown"
                class="action action toggle switcher-trigger"
                data-action="customer-menu-toggle">
                <span><?= $block->escapeHtml(__('Support')) ?></span>
            </div>
            <ul data-target="dropdown" class="dropdown-options">
                <?php echo $block->getChildChildHtml('ghratzoo_header.links') ?>
            </ul>
        </div>
        <?php echo $this->getChildHtml('currency') ?>
        <?php echo $this->getChildHtml('store_language') ?>
    </div>
    <div style="clear: both"></div>
</div>



